### ISSUE TITLE
Reference to type 'IConnectionConfigurationValues' claims it is defined in 'Elasticsearch.Net', but it could not be found

### ISSUE THREAD

**Issue by ahmadidev** [onuralp/Glimpse.ElasticSearch#3]
I installed `Glimpse.ElasticSearch` nuget package and tried to run your sample code but I got the following error in compile time.

Code:
```c#
var client = new ElasticClient(settings, new GlimpseHttpConnection(settings));
```

`Reference to type 'IConnectionConfigurationValues' claims it is defined in 'Elasticsearch.Net', but it could not be found`

Note that I'm using Nest client.

**Comment by onuralp** [comment]
Hi @ahmadidev ,

Thank you for reporting. I will check it.

**Comment by foresightyj** [comment]
I am experiencing the same issue, is it because I am using ES5 and NEST5?

**Comment by onuralp** [comment]
I just updated Elasticsearch.Net version to 5.2.0. Thank you for your patience
